FROM maven:3.8.3-openjdk-17 AS build
COPY . .

RUN mvn clean 
RUN mvn install

FROM openjdk:17.0.1-jdk-slim
COPY --from=build /target/okta-0.0.1-SNAPSHOT.jar okta.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","okta.jar"]
